<?php

return [
    [
        'id' => 'creator_027',
        'name' => 'OLA-WALÉ',
        'username' => 'olawal_14',
        'platforms' => [
            'tiktok' => '@olawal_14',
            'instagram' => null,
        ],
        'category' => 'Divertissement',
        'content_type' => ['divertissement', 'humour'],
        'city' => 'Cotonou',
        'country' => 'Bénin',
        'followers' => [
            'tiktok' => 1200000,
            'instagram' => null,
        ],
        'engagement_rate' => 9.41,
        'verified_data' => true,
    ],
    [
        'id' => 'creator_028',
        'name' => 'Ataou Ligali',
        'username' => 'ataoujotter1',
        'platforms' => [
            'tiktok' => '@ataoujotter1',
            'instagram' => null,
        ],
        'category' => 'Divertissement',
        'content_type' => ['divertissement', 'humour'],
        'city' => 'Cotonou',
        'country' => 'Bénin',
        'followers' => [
            'tiktok' => 1100000,
            'instagram' => null,
        ],
        'engagement_rate' => 20.93,
        'verified_data' => true,
    ],
    [
        'id' => 'creator_029',
        'name' => 'Tranquillin',
        'username' => 'tranquillinn',
        'platforms' => [
            'tiktok' => '@tranquillinn',
            'instagram' => '@tranquillinn',
        ],
        'category' => 'Divertissement',
        'content_type' => ['divertissement', 'lifestyle'],
        'city' => 'Cotonou',
        'country' => 'Bénin',
        'followers' => [
            'tiktok' => 1100000,
            'instagram' => 228100,
        ],
        'engagement_rate' => 15.75,
        'verified_data' => true,
    ],
    [
        'id' => 'creator_030',
        'name' => 'Carlo_O',
        'username' => 'carlo0fficiel',
        'platforms' => [
            'tiktok' => '@carlo0fficiel',
            'instagram' => null,
        ],
        'category' => 'Divertissement',
        'content_type' => ['divertissement', 'lifestyle'],
        'city' => 'Cotonou',
        'country' => 'Bénin',
        'followers' => [
            'tiktok' => 1100000,
            'instagram' => null,
        ],
        'engagement_rate' => 20.49,
        'verified_data' => true,
    ],
    [
        'id' => 'creator_031',
        'name' => 'Chef Rayane',
        'username' => 'chefrayanee',
        'platforms' => [
            'tiktok' => '@chefrayanee',
            'instagram' => null,
        ],
        'category' => 'Food',
        'content_type' => ['cuisine', 'gastronomie', 'food'],
        'city' => 'Cotonou',
        'country' => 'Bénin',
        'followers' => [
            'tiktok' => 1000000,
            'instagram' => null,
        ],
        'engagement_rate' => null,
        'verified_data' => true,
    ],
    [
        'id' => 'creator_032',
        'name' => 'Jojo le comédien',
        'username' => 'jojolecomedien',
        'platforms' => [
            'tiktok' => null,
            'instagram' => '@jojolecomedien',
        ],
        'category' => 'Humour',
        'content_type' => ['humour', 'comédie', 'divertissement'],
        'city' => 'Cotonou',
        'country' => 'Bénin',
        'followers' => [
            'tiktok' => null,
            'instagram' => 1500000,
        ],
        'engagement_rate' => 6.75,
        'verified_data' => true,
    ],
    [
        'id' => 'creator_033',
        'name' => 'Dr. Lawal ASSANI',
        'username' => 'blaazofficiel',
        'platforms' => [
            'tiktok' => null,
            'instagram' => '@blaazofficiel',
        ],
        'category' => 'Musique',
        'content_type' => ['musique', 'afrobeats', 'divertissement'],
        'city' => 'Cotonou',
        'country' => 'Bénin',
        'followers' => [
            'tiktok' => null,
            'instagram' => 623600,
        ],
        'engagement_rate' => 8.09,
        'verified_data' => true,
    ],
    [
        'id' => 'creator_034',
        'name' => 'Zeynab',
        'username' => 'zeynababibofficial1',
        'platforms' => [
            'tiktok' => null,
            'instagram' => '@zeynababibofficial1',
        ],
        'category' => 'Musique',
        'content_type' => ['musique', 'afrobeats', 'divertissement'],
        'city' => 'Cotonou',
        'country' => 'Bénin',
        'followers' => [
            'tiktok' => null,
            'instagram' => 482800,
        ],
        'engagement_rate' => 5.38,
        'verified_data' => true,
    ],
];