<?php

return [
    [
        'id' => 'creator_019',
        'name' => 'LADJAGAÏ',
        'username' => 'ladjagai.officiel',
        'platforms' => [
            'tiktok' => '@ladjagai.officiel',
            'instagram' => null,
        ],
        'category' => 'Divertissement',
        'content_type' => ['humour', 'création de contenu'],
        'city' => 'Cotonou',
        'country' => 'Bénin',
        'followers' => [
            'tiktok' => 1300000,
            'instagram' => null,
        ],
        'engagement_rate' => 20.45,
        'verified_data' => true,
    ],
    [
        'id' => 'creator_020',
        'name' => 'NIC TheSoftBoi',
        'username' => 'lenicofficiel',
        'platforms' => [
            'tiktok' => '@lenicofficiel',
            'instagram' => null,
        ],
        'category' => 'Divertissement',
        'content_type' => ['divertissement', 'lifestyle'],
        'city' => 'Cotonou',
        'country' => 'Bénin',
        'followers' => [
            'tiktok' => 1300000,
            'instagram' => null,
        ],
        'engagement_rate' => null,
        'verified_data' => true,
    ],
    [
        'id' => 'creator_021',
        'name' => 'PresidentDjangoun',
        'username' => 'lepresidentdjangoun',
        'platforms' => [
            'tiktok' => '@lepresidentdjangoun',
            'instagram' => null,
        ],
        'category' => 'Divertissement',
        'content_type' => ['humour', 'divertissement'],
        'city' => 'Cotonou',
        'country' => 'Bénin',
        'followers' => [
            'tiktok' => 1300000,
            'instagram' => null,
        ],
        'engagement_rate' => 12.55,
        'verified_data' => true,
    ],
    [
        'id' => 'creator_022',
        'name' => 'H-KONG',
        'username' => 'h_kong_eternal_',
        'platforms' => [
            'tiktok' => '@h_kong_eternal_',
            'instagram' => null,
        ],
        'category' => 'Divertissement',
        'content_type' => ['divertissement', 'humour'],
        'city' => 'Cotonou',
        'country' => 'Bénin',
        'followers' => [
            'tiktok' => 1300000,
            'instagram' => null,
        ],
        'engagement_rate' => 16.21,
        'verified_data' => true,
    ],
    [
        'id' => 'creator_023',
        'name' => 'Yénalia Lédémin',
        'username' => 'yenalia20',
        'platforms' => [
            'tiktok' => '@yenalia20',
            'instagram' => null,
        ],
        'category' => 'Lifestyle',
        'content_type' => ['lifestyle', 'divertissement'],
        'city' => 'Cotonou',
        'country' => 'Bénin',
        'followers' => [
            'tiktok' => 1300000,
            'instagram' => null,
        ],
        'engagement_rate' => 13.47,
        'verified_data' => true,
    ],
    [
        'id' => 'creator_024',
        'name' => 'Fada Comédy',
        'username' => 'fadacomedy',
        'platforms' => [
            'tiktok' => '@fadacomedy',
            'instagram' => null,
        ],
        'category' => 'Humour',
        'content_type' => ['humour', 'sketch', 'comédie'],
        'city' => 'Cotonou',
        'country' => 'Bénin',
        'followers' => [
            'tiktok' => 1200000,
            'instagram' => null,
        ],
        'engagement_rate' => null,
        'verified_data' => true,
    ],
    [
        'id' => 'creator_025',
        'name' => 'Ernest TV',
        'username' => 'ernest_tv',
        'platforms' => [
            'tiktok' => '@ernest_tv',
            'instagram' => null,
        ],
        'category' => 'Divertissement',
        'content_type' => ['divertissement', 'actualité'],
        'city' => 'Cotonou',
        'country' => 'Bénin',
        'followers' => [
            'tiktok' => 1200000,
            'instagram' => null,
        ],
        'engagement_rate' => 13.77,
        'verified_data' => true,
    ],
    [
        'id' => 'creator_026',
        'name' => 'Chef Kromo',
        'username' => 'chef_kromo',
        'platforms' => [
            'tiktok' => '@chef_kromo',
            'instagram' => null,
        ],
        'category' => 'Food',
        'content_type' => ['cuisine', 'food', 'gastronomie'],
        'city' => 'Cotonou',
        'country' => 'Bénin',
        'followers' => [
            'tiktok' => 1200000,
            'instagram' => null,
        ],
        'engagement_rate' => 13.97,
        'verified_data' => true,
    ],
];