<?php

return [
    [
        'id' => 'creator_011',
        'name' => 'Metis229',
        'username' => 'metis229',
        'platforms' => [
            'tiktok' => '@metis229',
            'instagram' => null,
        ],
        'category' => 'Divertissement',
        'content_type' => ['divertissement', 'humour'],
        'city' => 'Cotonou',
        'country' => 'Bénin',
        'followers' => [
            'tiktok' => 1600000,
            'instagram' => null,
        ],
        'engagement_rate' => null,
        'verified_data' => true,
    ],
    [
        'id' => 'creator_012',
        'name' => 'Gros229 T-Pharaons',
        'username' => 'gros_229',
        'platforms' => [
            'tiktok' => '@gros_229',
            'instagram' => null,
        ],
        'category' => 'Divertissement',
        'content_type' => ['humour', 'divertissement'],
        'city' => 'Cotonou',
        'country' => 'Bénin',
        'followers' => [
            'tiktok' => 1600000,
            'instagram' => null,
        ],
        'engagement_rate' => 18.89,
        'verified_data' => true,
    ],
    [
        'id' => 'creator_013',
        'name' => 'Habib Wilfreed Ahandessi',
        'username' => 'habib.ahandessi1',
        'platforms' => [
            'tiktok' => '@habib.ahandessi1',
            'instagram' => null,
        ],
        'category' => 'Actualité / Société',
        'content_type' => ['actualité', 'société', 'opinion'],
        'city' => 'Cotonou',
        'country' => 'Bénin',
        'followers' => [
            'tiktok' => 1600000,
            'instagram' => null,
        ],
        'engagement_rate' => 14.01,
        'verified_data' => true,
    ],
    [
        'id' => 'creator_014',
        'name' => 'FANICKO',
        'username' => 'fanickoofficiel',
        'platforms' => [
            'tiktok' => '@fanickoofficiel',
            'instagram' => '@fanickoofficiel',
        ],
        'category' => 'Musique',
        'content_type' => ['musique', 'afrobeats', 'divertissement'],
        'city' => 'Cotonou',
        'country' => 'Bénin',
        'followers' => [
            'tiktok' => 1400000,
            'instagram' => 1100000,
        ],
        'engagement_rate' => 20.23,
        'verified_data' => true,
    ],
    [
        'id' => 'creator_015',
        'name' => 'Ricko Dollars',
        'username' => 'ricko___dollars',
        'platforms' => [
            'tiktok' => '@ricko___dollars',
            'instagram' => null,
        ],
        'category' => 'Divertissement',
        'content_type' => ['divertissement', 'lifestyle'],
        'city' => 'Cotonou',
        'country' => 'Bénin',
        'followers' => [
            'tiktok' => 1400000,
            'instagram' => null,
        ],
        'engagement_rate' => 17.9,
        'verified_data' => true,
    ],
    [
        'id' => 'creator_016',
        'name' => 'Eden Food',
        'username' => 'eden_food',
        'platforms' => [
            'tiktok' => '@eden_food',
            'instagram' => null,
        ],
        'category' => 'Food',
        'content_type' => ['food', 'cuisine', 'gastronomie'],
        'city' => 'Cotonou',
        'country' => 'Bénin',
        'followers' => [
            'tiktok' => 1300000,
            'instagram' => null,
        ],
        'engagement_rate' => 8.53,
        'verified_data' => true,
    ],
    [
        'id' => 'creator_017',
        'name' => 'Kodey',
        'username' => 'kodeyofficiel',
        'platforms' => [
            'tiktok' => '@kodeyofficiel',
            'instagram' => null,
        ],
        'category' => 'Divertissement',
        'content_type' => ['divertissement', 'humour'],
        'city' => 'Cotonou',
        'country' => 'Bénin',
        'followers' => [
            'tiktok' => 1300000,
            'instagram' => null,
        ],
        'engagement_rate' => 12.89,
        'verified_data' => true,
    ],
    [
        'id' => 'creator_018',
        'name' => 'Mahougnon Officiel',
        'username' => 'mahougnon.officiel',
        'platforms' => [
            'tiktok' => '@mahougnon.officiel',
            'instagram' => null,
        ],
        'category' => 'Divertissement',
        'content_type' => ['humour', 'divertissement'],
        'city' => 'Cotonou',
        'country' => 'Bénin',
        'followers' => [
            'tiktok' => 1300000,
            'instagram' => null,
        ],
        'engagement_rate' => 13.39,
        'verified_data' => true,
    ],
];